// Package projects holds `revcat projects ...`.
package projects

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/akshitkrnagpal/revcat/internal/cliutil"
	"github.com/akshitkrnagpal/revcat/internal/output"
)

var Cmd = &cobra.Command{
	Use:     "projects",
	Aliases: []string{"proj"},
	Short:   "Inspect RevenueCat projects",
	Long: `A project is RevenueCat's top-level container - one per app or app
family. revcat resolves the active project from --project-id,
REVCAT_PROJECT_ID, the local .revcat/config.json written by
` + "`revcat init`" + `, or revcat.toml.

v2 exposes project create + list. There is no v2 update or delete by
id; manage those in the dashboard.`,
}

func init() {
	Cmd.AddCommand(listCmd)
	Cmd.AddCommand(viewCmd)
	Cmd.AddCommand(createCmd)
}

var listCmd = &cobra.Command{
	Use:   "list",
	Short: "List projects accessible to this credential",
	RunE: func(cmd *cobra.Command, args []string) error {
		client, _, err := cliutil.Client(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := context.WithTimeout(cmd.Context(), 30*time.Second)
		defer cancel()
		projects, err := client.ListProjects(ctx)
		if err != nil {
			return err
		}
		rows := make([][]any, 0, len(projects))
		for _, p := range projects {
			rows = append(rows, []any{p.ID, p.Name, formatTime(p.CreatedAt)})
		}
		return output.Table([]string{"id", "name", "created"}, rows)
	},
}

var viewCmd = &cobra.Command{
	Use:   "view [id]",
	Short: "Show one project by id (defaults to the resolved project)",
	Args:  cobra.RangeArgs(0, 1),
	RunE: func(cmd *cobra.Command, args []string) error {
		client, prof, err := cliutil.Client(cmd)
		if err != nil {
			return err
		}
		id := cliutil.ResolveProjectID(cmd, prof)
		if len(args) == 1 {
			id = args[0]
		}
		if id == "" {
			return errProjectIDRequired
		}
		ctx, cancel := context.WithTimeout(cmd.Context(), 30*time.Second)
		defer cancel()
		p, raw, err := client.GetProjectRaw(ctx, id)
		if err != nil {
			return err
		}
		if output.IsJSON() {
			return output.JSON(raw)
		}
		rows := [][]any{
			{"id", p.ID},
			{"name", p.Name},
			{"created", formatTime(p.CreatedAt)},
		}
		return output.Table([]string{"field", "value"}, rows)
	},
}

var createName string

var createCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new project",
	Long: `Create a new project at the account level.

The project id is generated by RevenueCat and printed on success;
quote it (or pipe with --output json) to feed into ` + "`revcat init`" + ` or
` + "`--project-id`" + ` for follow-up commands.

Examples:
    revcat projects create --name "My App"
    revcat projects create --name staging --output json | jq -r .id`,
	RunE: func(cmd *cobra.Command, args []string) error {
		name := strings.TrimSpace(createName)
		if name == "" {
			return errors.New("--name is required")
		}
		client, _, err := cliutil.Client(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := context.WithTimeout(cmd.Context(), 30*time.Second)
		defer cancel()
		p, err := client.CreateProject(ctx, name)
		if err != nil {
			return err
		}
		if output.IsJSON() {
			return output.JSON(p)
		}
		rows := [][]any{
			{"id", p.ID},
			{"name", p.Name},
			{"created", formatTime(p.CreatedAt)},
		}
		return output.Table([]string{"field", "value"}, rows)
	},
}

func init() {
	createCmd.Flags().StringVar(&createName, "name", "", "Project name (required)")
}

func formatTime(unix int64) string {
	if unix == 0 {
		return "-"
	}
	t := time.Unix(unix, 0).UTC()
	if unix > 9999999999 {
		t = time.UnixMilli(unix).UTC()
	}
	return t.Format("2006-01-02")
}

type sentinelErr string

func (e sentinelErr) Error() string { return string(e) }

const errProjectIDRequired = sentinelErr("no project id given and active profile has none; pass <id>")
